# This Service gives the alert-monitor a stable network address.
apiVersion: v1
kind: Service
metadata:
  name: alert-monitor
spec:
  selector:
    app: alert-monitor
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
