# k8s/overlays/development/kustomization.yaml
# This Kustomization file defines the 'development' environment.
# It takes the generic 'base' configuration and applies specific
# settings for development, such as image tags and the namespace.

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# This line tells Kustomize to use everything from our 'base' directory
# as a foundation for this overlay.
bases:
  - ../../base

# This ensures all resources deployed via this overlay will be created
# in the 'fraud-detection' namespace, keeping our cluster organized.
namespace: fraud-detection

# The 'images' block is the core of an overlay. It finds container images
# by their 'name' in the base manifests (e.g., 'placeholder-repo/payment-api')
# and replaces them with a real repository path ('newName') and a specific version ('newTag').
# This allows us to update a single service without rebuilding everything.
images:
  - name: placeholder-repo/payment-api
    newName: ghcr.io/mordris/payment-api
    newTag: v0.0.3
  - name: placeholder-repo/alert-monitor
    newName: ghcr.io/mordris/alert-monitor
    newTag: v0.0.1
  - name: placeholder-repo/flink-app
    newName: ghcr.io/mordris/flink-app
    newTag: v0.0.2
