# k8s/base/flink/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: flink-config
data:
  # This key is now needed by the TaskManager.
  FLINK_PROPERTIES: |
    jobmanager.rpc.address: flink-jobmanager
    taskmanager.numberOfTaskSlots: 2
  # These keys are still needed by the Python script.
  KAFKA_BROKER: "redpanda-0.redpanda.fraud-detection.svc.cluster.local:9093"
  REDIS_HOST: "redis-master.fraud-detection.svc.cluster.local"
