# k8s/base/flink/job-submitter.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: flink-job-submitter
  # This is correct and necessary. It tells Argo CD to replace the job on change.
  annotations:
    argocd.argoproj.io/sync-options: Replace=true
spec:
  # It's good practice to set a timeout for job submission
  activeDeadlineSeconds: 120
  # The 'selector' block has been REMOVED.
  template:
    metadata:
      # The 'labels' block has been REMOVED.
      # Kubernetes will add its own required labels here automatically.
    spec:
      containers:
        - name: flink-job-submitter
          image: placeholder-repo/flink-app:latest
          command:
            [
              "/opt/flink/bin/flink",
              "run",
              "-d",
              "-py",
              "/opt/flink/usrlib/fraud_detector.py",
              "-m",
              "flink-jobmanager:8081",
            ]
          # This is correct and necessary.
          envFrom:
            - configMapRef:
                name: flink-config
      restartPolicy: OnFailure
