# k8s/base/flink/job-submitter.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: flink-job-submitter
  # --- ADD THIS ANNOTATION ---
  annotations:
    argocd.argoproj.io/sync-options: Replace=true
  # ---------------------------
spec:
  activeDeadlineSeconds: 120
  template:
    spec:
      containers:
        - name: flink-job-submitter
          image: placeholder-repo/flink-app:latest # This will be replaced by Kustomize
          command:
            [
              "/opt/flink/bin/flink",
              "run",
              "-d",
              "-py",
              "/opt/flink/usrlib/fraud_detector.py",
              "-m",
              "flink-jobmanager:8081",
            ]
      restartPolicy: OnFailure
