# k8s/base/flink/job-submitter.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: flink-job-submitter
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  # --- CHANGE THIS VALUE ---
  # Increase the timeout to 5 minutes (300 seconds) to give the Flink
  # cluster plenty of time to start before the submission times out.
  activeDeadlineSeconds: 300

  # --- ADD THIS LINE ---
  # If the pod fails (e.g., can't connect), retry up to 2 times.
  backoffLimit: 2
  # ---------------------
  template:
    spec:
      containers:
        - name: flink-job-submitter
          image: placeholder-repo/flink-app:latest
          command:
            [
              "/opt/flink/bin/flink",
              "run",
              "-d",
              "-py",
              "/opt/flink/usrlib/fraud_detector.py",
              "-m",
              "flink-jobmanager:8081",
            ]
          envFrom:
            - configMapRef:
                name: flink-config
      restartPolicy: OnFailure
