# k8s/base/flink/job-submitter.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: flink-job-submitter
  # --- ADD THIS ANNOTATION ---
  # This tells Argo CD to delete the old Job and create a new one
  # instead of trying to patch the immutable template fields.
  annotations:
    argocd.argoproj.io/sync-options: Replace=true
  # ---------------------------
spec:
  # It's good practice to set a timeout for job submission
  activeDeadlineSeconds: 120
  template:
    spec:
      containers:
        - name: flink-job-submitter
          image: placeholder-repo/flink-app:latest
          command: [
              "/opt/flink/bin/flink",
              "run",
              "-d", # Run in detached mode
              "-py",
              "/opt/flink/usrlib/fraud_detector.py",
              "-m",
              "flink-jobmanager:8081",
            ]
          # This ensures the Python script reads the correct Kubernetes service
          # names for Kafka and Redis when it is submitted to the cluster.
          envFrom:
            - configMapRef:
                name: flink-config
      restartPolicy: OnFailure
