# k8s/base/flink/job-submitter.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: flink-job-submitter
  # --- REPLACE THE OLD ANNOTATION WITH THESE TWO ---
  annotations:
    # This designates the Job as a task to run during the sync phase.
    argocd.argoproj.io/hook: Sync
    # This tells Argo CD to automatically delete this Job after it succeeds.
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
  # ----------------------------------------------------
spec:
  # It's good practice to set a timeout for job submission
  activeDeadlineSeconds: 120
  # We no longer need the selector or labels, Kubernetes will handle it for this transient job.
  template:
    spec:
      containers:
        - name: flink-job-submitter
          image: placeholder-repo/flink-app:latest
          command:
            [
              "/opt/flink/bin/flink",
              "run",
              "-d",
              "-py",
              "/opt/flink/usrlib/fraud_detector.py",
              "-m",
              "flink-jobmanager:8081",
            ]
          envFrom:
            - configMapRef:
                name: flink-config
      restartPolicy: OnFailure
