# k8s/base/flink/job-submitter.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: flink-job-submitter
  annotations:
    # Designates the Job as a task to run during the sync phase.
    argocd.argoproj.io/hook: Sync
    # Before creating this hook, delete any previous instance of it.
    # This is more robust than waiting for success.
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  # Increase the timeout to 5 minutes (300 seconds) to ensure the
  # Flink cluster has time to start up.
  activeDeadlineSeconds: 300

  # If the pod fails, retry up to 2 times.
  backoffLimit: 2
  template:
    spec:
      containers:
        - name: flink-job-submitter
          image: placeholder-repo/flink-app:latest
          command:
            [
              "/opt/flink/bin/flink",
              "run",
              "-d",
              "-py",
              "/opt/flink/usrlib/fraud_detector.py",
              "-m",
              "flink-jobmanager:8081",
            ]
          envFrom:
            - configMapRef:
                name: flink-config
      restartPolicy: OnFailure
