# k8s/base/flink/job-submitter.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: flink-job-submitter
  annotations:
    argocd.argoproj.io/sync-options: Replace=true
spec:
  # It's good practice to set a timeout for job submission
  activeDeadlineSeconds: 120
  # --- ADD THIS SELECTOR ---
  # This tells the Job how to find the pods it creates.
  selector:
    matchLabels:
      app: flink-job-submitter
  # -------------------------
  template:
    metadata:
      # --- ADD THESE LABELS ---
      # This applies the required labels to the pods created by this Job.
      # The labels must match the spec.selector.matchLabels above.
      labels:
        app: flink-job-submitter
      # ------------------------
    spec:
      containers:
        - name: flink-job-submitter
          image: placeholder-repo/flink-app:latest # This will be replaced by Kustomize
          command:
            [
              "/opt/flink/bin/flink",
              "run",
              "-d",
              "-py",
              "/opt/flink/usrlib/fraud_detector.py",
              "-m",
              "flink-jobmanager:8081",
            ]
          envFrom:
            - configMapRef:
                name: flink-config
      restartPolicy: OnFailure
