# k8s/base/flink/jobmanager-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flink-jobmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flink
      component: jobmanager
  template:
    metadata:
      labels:
        app: flink
        component: jobmanager
    spec:
      containers:
        - name: flink-jobmanager
          image: placeholder-repo/flink-app:latest
          args: ["jobmanager"]
          ports:
            - containerPort: 8081
              name: webui
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: FLINK_PROPERTIES
              value: "jobmanager.rpc.address: flink-jobmanager\nrest.address: $(POD_IP)\n"
          # --- ADD THIS SECTION ---
          # This gives the JobManager process the KAFKA_BROKER and REDIS_HOST
          # variables, which are needed by the Python script's coordinator.
          envFrom:
            - configMapRef:
                name: flink-config
          # --- END OF ADDED SECTION ---
