# This Deployment is for the Flink TaskManagers (the worker nodes).
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flink-taskmanager
spec:
  replicas: 1 # We will start with one worker. We can easily scale this later.
  selector:
    matchLabels:
      app: flink
      component: taskmanager
  template:
    metadata:
      labels:
        app: flink
        component: taskmanager
    spec:
      containers:
        - name: flink-taskmanager
          image: placeholder-repo/flink-app:latest
          # This overrides the CMD to start a taskmanager instead.
          args: ["taskmanager"]
          env:
            - name: FLINK_PROPERTIES
              valueFrom:
                configMapKeyRef:
                  name: flink-config
                  key: FLINK_PROPERTIES
