# k8s/base/flink/taskmanager-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flink-taskmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flink
      component: taskmanager
  template:
    metadata:
      labels:
        app: flink
        component: taskmanager
    spec:
      containers:
        - name: flink-taskmanager
          image: placeholder-repo/flink-app:latest
          args: ["taskmanager"]
          # This tells the TaskManager to load the FLINK_PROPERTIES
          # from our corrected ConfigMap.
          envFrom:
            - configMapRef:
                name: flink-config
