# k8s/overlays/staging/kustomization.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Use the same base manifests as development
bases:
  - ../../base

# This is the crucial instruction that tells Kustomize to apply the
# 'fraud-detection-staging' namespace to ALL resources it generates.
namespace: fraud-detection-staging

# The image tags in this file will be updated by the promotion PR process.
# For now, they can be the same as development.
images:
  - name: placeholder-repo/payment-api
    newName: ghcr.io/mordris/payment-api
    newTag: 54d2be72d3d2326ca5ac7771c5f686db52 # Example tag
  - name: placeholder-repo/alert-monitor
    newName: ghcr.io/mordris/alert-monitor
    newTag: aaa37eaa241b96e4e57f65f2f9ce3500f977ed17 # Example tag
  - name: placeholder-repo/flink-app
    newName: ghcr.io/mordris/flink-app
    newTag: 4bd4277ed1633dc4ddc909b168a52c14ce774f12 # Example tag
